<?php


namespace App\Transformers\ProductCategory;


use App\Models\ProductCategory;

class ListAdminProductCategoryTransformer extends BaseProductCategoryTransformer
{
    public function transform(ProductCategory $entry)
    {
        return parent::transform($entry); // TODO: Change the autogenerated stub
    }
}
