<?php


namespace App\Transformers\Page;


use App\Models\Page;

class ListAdminPageTransformer extends BasePageTransformer
{
    public function transform(Page $entry)
    {
        return parent::transform($entry); // TODO: Change the autogenerated stub
    }
}
