<?php


namespace App\Transformers\ListSlider;


use App\Models\ListSlider;

class ListAdminSliderTransformer extends BaseListSliderTransformer
{
    public function transform(ListSlider $entry)
    {
        return parent::transform($entry); // TODO: Change the autogenerated stub
    }
}
