<?php


namespace App\Transformers\Product;


use App\Models\Product;

class ListAdminProductTransformer extends BaseProductTransformer
{
        public function transform(Product $entry)
        {
            $data = parent::transform($entry); // TODO: Change the autogenerated stub
            $data['nameCategory'] = @$entry->productCategory->name;
            return $data;
        }
}
