<?php


namespace App\Transformers\Combo;


use App\Models\Combo;

class ListComboAdminTransformer extends BaseComboTransformer
{
    public function transform(Combo $entry)
    {
        $data = parent::transform($entry); // TODO: Change the autogenerated stub
        $data['nameCategory'] = @$entry->productCategory->name;
        $data['products'] = $entry->products? $entry->products->toArray() : [];
        return $data;
    }
}
